"""Add order_invitations table

Revision ID: fa23b53873b1
Revises: 
Create Date: 2025-11-26 00:13:19.383666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa23b53873b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('profile_image', sa.String(length=1024), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('completed_orders', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('total_earned', sa.Float(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('application_status', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('notification_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('last_read', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('sender_id', sa.String(length=50), nullable=True),
    sa.Column('user_email', sa.String(length=100), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_group', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('client_id', sa.String(length=50), nullable=True),
    sa.Column('writer_id', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('minimum_allowed_budget', sa.Float(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('detailed_requirements', sa.Text(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['writer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_methods',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('writer_applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('education', sa.String(length=120), nullable=True),
    sa.Column('specialization', sa.String(length=120), nullable=True),
    sa.Column('years_experience', sa.String(length=50), nullable=True),
    sa.Column('selected_prompt', sa.String(length=255), nullable=True),
    sa.Column('prompt_response', sa.Text(), nullable=True),
    sa.Column('selected_essay_topic', sa.String(length=255), nullable=True),
    sa.Column('essay_file_path', sa.String(length=255), nullable=True),
    sa.Column('proficiency_answers', sa.JSON(), nullable=True),
    sa.Column('work_samples', sa.JSON(), nullable=True),
    sa.Column('degree_certificates', sa.JSON(), nullable=True),
    sa.Column('cv_file_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('admin_feedback', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bids',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('bid_amount', sa.Float(), nullable=False),
    sa.Column('original_budget', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_counter_offer', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('response_deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bids_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bids_user_id'), ['user_id'], unique=False)

    op.create_table('chats',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.String(length=50), nullable=False),
    sa.Column('writer_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('warning_risk', sa.String(length=20), nullable=True),
    sa.Column('warning_message', sa.Text(), nullable=True),
    sa.Column('warning_expires_at', sa.DateTime(), nullable=True),
    sa.Column('warning_active', sa.Boolean(), nullable=True),
    sa.Column('warning_for_user_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['writer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'client_id', 'writer_id', name='uq_chat_order_client_writer')
    )
    op.create_table('declined_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('writer_id', sa.String(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['writer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_invitations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('writer_id', sa.String(length=50), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['writer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('chat_id', sa.String(length=50), nullable=True),
    sa.Column('sender_id', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('geography_columns')
    # op.drop_table('geometry_columns')
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    comment="Shows all defined Spatial Reference Identifiers (SRIDs). Matches PostGIS' spatial_ref_sys table."
    )
    op.create_table('geometry_columns',
    sa.Column('f_table_catalog', sa.String(), autoincrement=False, nullable=True),
    sa.Column('f_table_schema', sa.String(), autoincrement=False, nullable=True),
    sa.Column('f_table_name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('f_geometry_column', sa.String(), autoincrement=False, nullable=True),
    sa.Column('coord_dimension', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('srid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    comment="Shows all defined geometry columns. Matches PostGIS' geometry_columns functionality."
    )
    op.create_table('geography_columns',
    sa.Column('f_table_catalog', sa.String(), autoincrement=False, nullable=True),
    sa.Column('f_table_schema', sa.String(), autoincrement=False, nullable=True),
    sa.Column('f_table_name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('f_geography_column', sa.String(), autoincrement=False, nullable=True),
    sa.Column('coord_dimension', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('srid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    comment="Shows all defined geography columns. Matches PostGIS' geography_columns functionality."
    )
    op.drop_table('messages')
    op.drop_table('order_invitations')
    op.drop_table('declined_orders')
    op.drop_table('chats')
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bids_user_id'))
        batch_op.drop_index(batch_op.f('ix_bids_order_id'))

    op.drop_table('bids')
    op.drop_table('writer_applications')
    op.drop_table('transactions')
    op.drop_table('payment_methods')
    op.drop_table('orders')
    op.drop_table('notifications')
    op.drop_table('notification_reads')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
